import { Plus_Jakarta_Sans, Inter } from "next/font/google";
import "./globals.css";
import "./swiper-custom.css";
import NextAuthProvider from "@/provider/NextAuthProvider";

const inter = Inter({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
  variable: "--font-inter",
});

const jakarta = Plus_Jakarta_Sans({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  variable: "--font-jakarta",
});

export const metadata = {
  title: {
    default: "Together In Community",
    template: "%s | Together In Community",
  },
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <NextAuthProvider>
      <html lang="en">
      <body
        className={`${inter.className} ${jakarta.className} antialiased`}
        suppressHydrationWarning={true}
      >
        <header className="sticky top-0 z-50">
          <div className="w-full">
            <Navbar></Navbar>
          </div>
        </header>
        
        <main className="min-h-[calc(100vh-302px)]">{children}</main>

        <footer className="w-full">
          <Footer></Footer>
        </footer>

        <div className="fixed bottom-6 right-2 z-50">
          <Chat />
        </div>
      </body>
    </html>
    </NextAuthProvider>
  );
}
