import { Plus_Jakarta_Sans, Inter } from "next/font/google";
import "./globals.css";
import "./swiper-custom.css";
import NextAuthProvider from "@/provider/NextAuthProvider";

const inter = Inter({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
  variable: "--font-inter",
});

const jakarta = Plus_Jakarta_Sans({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  variable: "--font-jakarta",
});

export const metadata = {
  title: {
    default: "Together In Community",
    template: "%s | Together In Community",
  },
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <NextAuthProvider>
      <html lang="en">
      <body
        className={`${inter.className} ${jakarta.className} antialiased`}
        suppressHydrationWarning={true}
      >
        {children}
      </body>
    </html>
    </NextAuthProvider>
  );
}
